Rocky/Models/ApplicationType.cs
using System.ComponentModel.DataAnnotations;

namespace Rocky.Models
{
    public class ApplicationType
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
    }
}

Rocky/Models/Category.cs
using System.ComponentModel.DataAnnotations;

namespace Rocky.Models
{
    public class Category
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "Display Order for category must be greater than zero")]
        public int DisplayOrder { get; set; }
    }
}

Rocky/Models/ErrorViewModel.cs
using System;

namespace Rocky.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Rocky/Models/Product.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rocky.Models
{
    public class Product
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        public string Description { get; set; }
        [Range(1, int.MaxValue)]
        public double Price { get; set; }
        public string Image { get; set; }
        [Display(Name = "Category Type")]
        public int CategoryId { get; set; }
        [ForeignKey("CategoryId")]
        public virtual Category Category { get; set; }
    }
}

Rocky/Models/ViewModels/ProductVM.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Rocky.Models.ViewModels
{
    public class ProductVM
    {
        public IEnumerable<SelectListItem> CategorySelectList { get; set; }
        public Product Product { get; set; }
    }
}

Rocky/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Rocky.Data;
using Rocky.Models;

namespace Rocky.Controllers
{
    public class CategoryController : Controller
    {

        private readonly ApplicationDbContext _db;

        public CategoryController(ApplicationDbContext db)
        {
            _db = db;
        }
        // GET
        public IActionResult Index()
        {
            IEnumerable<Category> categories = _db.Category;
            return View(categories);
        }
        // GET - CREATE
        public IActionResult Create()
        {
            return View();
        }
        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category cat)
        {
            if (!ModelState.IsValid)
            {
                return View(cat);
            }
            _db.Category.Add(cat);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET - EDIT
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var cat = _db.Category.Find(id);
            if (cat == null)
            {
                return NotFound();
            }

            return View(cat);
        }
        
        // POST - EDIT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category cat)
        {
            if (!ModelState.IsValid)
            {
                return View(cat);
            }
            _db.Category.Update(cat);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        
        // GET - DELETE
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var cat = _db.Category.Find(id);
            if (cat == null)
            {
                return NotFound();
            }

            return View(cat);
        }
        
        // POST - EDIT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(Category cat)
        {
            cat = _db.Category.Find(cat.Id);
            if (cat == null)
            {
                return NotFound();
            }
            _db.Category.Remove(cat);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Rocky/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Rocky.Models;

namespace Rocky.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Rocky/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Rocky.Data;
using Rocky.Models;
using Rocky.Models.ViewModels;

namespace Rocky.Controllers
{
    public class ProductController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ProductController(ApplicationDbContext db)
        {
            _db = db;
        }
        
        // GET products list page
        public IActionResult Index()
        {
            IEnumerable<Product> products = _db.Product;
            
            return View(products);
        }

        // GET product page
        public IActionResult Upsert(int? id)
        {
            var productVm = new ProductVM
            {
                Product = new Product(),
                CategorySelectList = _db.Category.Select(category => new SelectListItem
                {
                    Text = category.Name,
                    Value = category.Id.ToString()
                })
            };
                
            if (id == null)
            {
                return View(productVm);
            }
            productVm.Product = _db.Product.Find(id);
            if (productVm.Product == null)
            {
                return NotFound();
            }
            return View(productVm);
        }

        // POST new or existing product
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(ProductVM productVm)
        {
            if (ModelState.IsValid)
            {
                return RedirectToAction("Index");
            }

            return View(productVm);
        }

        public IActionResult Delete(int? id)
        {
            return View();
        }
    }
}

Rocky/Views/Category/Index.cshtml
@model IEnumerable<Category> 

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Category List</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="Category" asp-action="Create" class="btn btn-primary"> 
            <i class="fa-solid fa-plus"></i>&nbsp; Create new Category
            </a>
        </div>
    </div>
    
    <br/> <br/>
    
    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width: 100%">
            <thead>
            <tr>
                <th>
                    Category Name
                </th>
                <th>
                    Display Order
                </th>
                <th></th>
            </tr>
            </thead>
            <tbody>
                @foreach (var cat in Model)
                {
                    <tr>
                        <td style="width: 50%">@cat.Name</td>
                        <td style="width: 30%">@Convert.ToString(cat.DisplayOrder)</td>
                        <td class="text-center">
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="Category" asp-route-Id="@Convert.ToString(cat.Id)" asp-action="Edit" class="btn btn-primary"> 
                                    <i class="fa-solid fa-pen-to-square"></i>
                                </a>
                                <a asp-controller="Category" asp-route-Id="@Convert.ToString(cat.Id)" asp-action="Delete" class="btn btn-danger"> 
                                    <i class="fa-solid fa-trash-can"></i>
                                </a>
                                
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
</div>

Rocky/Views/Category/create.cshtml
@model Category

<form method="post" asp-action="Create">
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-info pl-3">Add category</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name">Name</label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control"/>
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="DisplayOrder">Display Order</label>
                    </div>
                    <div class="col-8">
                        <input asp-for="DisplayOrder" class="form-control"/>
                        <span asp-validation-for="DisplayOrder" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Create"/>
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-primary"><i class="fa-solid fa-arrow-right-from-bracket"></i> Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts
{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Rocky/Views/Category/delete.cshtml
@model Category

<form method="post" asp-action="Delete">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-info pl-3">Delete category</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name">Name</label>
                    </div>
                    <div class="col-8">
                        <input readonly asp-for="Name" class="form-control"/>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="DisplayOrder">Display Order</label>
                    </div>
                    <div class="col-8">
                        <input readonly asp-for="DisplayOrder" class="form-control"/>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" class="btn btn-danger w-100" value="Delete"/>
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-primary"><i class="fa-solid fa-arrow-right-from-bracket"></i> Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts
{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Rocky/Views/Category/edit.cshtml
@model Category

<form method="post" asp-action="Edit">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-info pl-3">Edit category</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name">Name</label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control"/>
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="DisplayOrder">Display Order</label>
                    </div>
                    <div class="col-8">
                        <input asp-for="DisplayOrder" class="form-control"/>
                        <span asp-validation-for="DisplayOrder" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Update"/>
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-primary"><i class="fa-solid fa-arrow-right-from-bracket"></i>Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts
{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Rocky/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Rocky/Views/Product/Upsert.cshtml
@model Rocky.Models.ViewModels.ProductVM

@{
    var title = "Create Product";
}

<form method="post" enctype="multipart/form-data">
    @if (Model.Product.Id != 0)
    {
        title = "Edit Product";
        <input asp-for="Product.Id" hidden/>
    }
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-info pl-3">@title</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Product.Name">Name</label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Product.Name" class="form-control"/>
                        <span asp-validation-for="Product.Name" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Product.Price">Price</label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Product.Price" class="form-control"/>
                        <span asp-validation-for="Product.Price" class="text-danger"></span>
                    </div>
                </div>
                
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Product.Description">Description</label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Product.Description" class="form-control"/>
                        <span asp-validation-for="Product.Description" class="text-danger"></span>
                    </div>
                </div>
                
                <div class="form-group row">
                    <div class="col-4">
                        Image
                    </div>
                    <div class="col-8">
                        <input type="file" name="files" id="uploadBox" multiple class="form-control"/>
                    </div>
                </div>
                
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Product.CategoryId">Display Order</label>
                    </div>
                    <div class="col-8">
                        <select asp-for="Product.CategoryId" asp-items="@Model.CategorySelectList" class="form-control">
                            <option disabled selected>--Select Category--</option>
                        </select>
                        <span asp-validation-for="Product.CategoryId" class="text-danger"></span>
                    </div>
                </div>
                
                <div class="form-group row">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            @if (Model.Product.Id != 0)
                            {
                                //update
                                <input type="submit" class="btn btn-info w-100" value="Update"/>

                            }
                            else
                            {
                                //create
                                <input type="submit" onclick="return validateInput()" class="btn btn-primary w-100" value="Create"/>

                            }
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-primary"><i class="fa-solid fa-arrow-right-from-bracket"></i>Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts
{
    @{
        <partial name="_ValidationScriptsPartial"/>
    }

    <script>
        function validateInput() {
            if (document.getElementById('uploadBox').value === '') {
                Swal.fire(
                  'Error',
                  'Please upload an Image!',
                  'error'
                )
                return false;
            }  
            return true;
        }
    </script>
}

Rocky/Views/Product/index.cshtml
@model IEnumerable<Product> 

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Product List</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-action="Upsert" class="btn btn-primary"> 
                <i class="fa-solid fa-plus"></i>&nbsp; Create new Product
            </a>
        </div>
    </div>
    
    <br/> <br/>
    
    @if (Model.Any())
    {
        <table class="table table-bordered table-striped" style="width: 100%">
            <thead>
            <tr>
                <th>
                    Product Name
                </th>
                <th>
                    Price
                </th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            @foreach (var product in Model)
            {
                <tr>
                    <td style="width: 50%">@product.Name</td>
                    <td style="width: 30%">@Convert.ToString(product.Price)</td>
                    <td class="text-center">
                        <div class="w-75 btn-group" role="group">
                            <a asp-route-Id="@Convert.ToString(product.Id)" asp-action="Upsert" class="btn btn-primary"> 
                                <i class="fa-solid fa-pen-to-square"></i>
                            </a>
                            <a asp-route-Id="@Convert.ToString(product.Id)" asp-action="Delete" class="btn btn-danger"> 
                                <i class="fa-solid fa-trash-can"></i>
                            </a>
                                
                        </div>
                    </td>
                </tr>
            }
            </tbody>
        </table>
    }
</div>

Rocky/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Rocky</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Rocky</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2022 - Rocky - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://kit.fontawesome.com/2d16f5124d.js" crossorigin="anonymous"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>